Name: Settings
Type: FolderType
Children:
- Name: FolderPath
  Id: g=4f1b9f29f94e190975396444e5b1090b
  Type: BaseDataVariableType
  DataType: AbsoluteResourceUri
  Value: "%PROJECTDIR%\\CSV"
- Name: PLC_URL
  Id: g=943bc971a73a07d75a8da48772c983a5
  Type: BaseDataVariableType
  DataType: String
  Value: "127.0.0.1"
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../CommDrivers/Water Plant/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Route"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: PDF_Output_Path
  Id: g=b75f90252ff336ea7f54032228d2e1ab
  Type: BaseDataVariableType
  DataType: String
  Value: "C:\\Shared Files - Process Room\\FT Optix Files\\SandBox_Energy\\ProjectFiles\\PDF\\DataReport.pdf"
- Name: Query_Max_Values
  Id: g=855f20ff07b1db84bc39a9a855cbcdb6
  Type: BaseDataVariableType
  DataType: String
  Value: "SELECT * FROM \"DataLogger1\" limit 20"
